### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mmatongo** [AlfredoSequeida/venus#9]
It hasn't been working for the last couple of weeks on my bspwm set up. This is what I get.

➜  ~ venus
Traceback (most recent call last):
  File "/usr/bin/venus", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'venuspy==1.0.1' distribution was not found and is required by the application

**Comment by AlfredoSequeida** [comment]
Hit this is because of the recent update. I believe It might have been pushed separately and therefore the package is missing. 

The fix is just to reinstall venus
`pip3 install venuspy`

Everything should work after that. Let me know if that works for you.

**Comment by mmatongo** [comment]
The commands need to be run as `sudo`, running them as a regular user doesn't work.
